/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { MenuItem } from "./MenuItem";
import { MenuItemCountArgs } from "./MenuItemCountArgs";
import { MenuItemFindManyArgs } from "./MenuItemFindManyArgs";
import { MenuItemFindUniqueArgs } from "./MenuItemFindUniqueArgs";
import { CreateMenuItemArgs } from "./CreateMenuItemArgs";
import { UpdateMenuItemArgs } from "./UpdateMenuItemArgs";
import { DeleteMenuItemArgs } from "./DeleteMenuItemArgs";
import { FavoriteMenuItemFindManyArgs } from "../../favoriteMenuItem/base/FavoriteMenuItemFindManyArgs";
import { FavoriteMenuItem } from "../../favoriteMenuItem/base/FavoriteMenuItem";
import { MenuItemCategoryFindManyArgs } from "../../menuItemCategory/base/MenuItemCategoryFindManyArgs";
import { MenuItemCategory } from "../../menuItemCategory/base/MenuItemCategory";
import { OrderItemFindManyArgs } from "../../orderItem/base/OrderItemFindManyArgs";
import { OrderItem } from "../../orderItem/base/OrderItem";
import { Menu } from "../../menu/base/Menu";
import { MenuItemService } from "../menuItem.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MenuItem)
export class MenuItemResolverBase {
  constructor(
    protected readonly service: MenuItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MenuItem",
    action: "read",
    possession: "any",
  })
  async _menuItemsMeta(
    @graphql.Args() args: MenuItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MenuItem])
  @nestAccessControl.UseRoles({
    resource: "MenuItem",
    action: "read",
    possession: "any",
  })
  async menuItems(
    @graphql.Args() args: MenuItemFindManyArgs
  ): Promise<MenuItem[]> {
    return this.service.menuItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MenuItem, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MenuItem",
    action: "read",
    possession: "own",
  })
  async menuItem(
    @graphql.Args() args: MenuItemFindUniqueArgs
  ): Promise<MenuItem | null> {
    const result = await this.service.menuItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MenuItem)
  @nestAccessControl.UseRoles({
    resource: "MenuItem",
    action: "create",
    possession: "any",
  })
  async createMenuItem(
    @graphql.Args() args: CreateMenuItemArgs
  ): Promise<MenuItem> {
    return await this.service.createMenuItem({
      ...args,
      data: {
        ...args.data,

        menuItemCategoriesMenuItemsCategoryIdToMenuItemCategories: args.data
          .menuItemCategoriesMenuItemsCategoryIdToMenuItemCategories
          ? {
              connect:
                args.data
                  .menuItemCategoriesMenuItemsCategoryIdToMenuItemCategories,
            }
          : undefined,

        menus: args.data.menus
          ? {
              connect: args.data.menus,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MenuItem)
  @nestAccessControl.UseRoles({
    resource: "MenuItem",
    action: "update",
    possession: "any",
  })
  async updateMenuItem(
    @graphql.Args() args: UpdateMenuItemArgs
  ): Promise<MenuItem | null> {
    try {
      return await this.service.updateMenuItem({
        ...args,
        data: {
          ...args.data,

          menuItemCategoriesMenuItemsCategoryIdToMenuItemCategories: args.data
            .menuItemCategoriesMenuItemsCategoryIdToMenuItemCategories
            ? {
                connect:
                  args.data
                    .menuItemCategoriesMenuItemsCategoryIdToMenuItemCategories,
              }
            : undefined,

          menus: args.data.menus
            ? {
                connect: args.data.menus,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MenuItem)
  @nestAccessControl.UseRoles({
    resource: "MenuItem",
    action: "delete",
    possession: "any",
  })
  async deleteMenuItem(
    @graphql.Args() args: DeleteMenuItemArgs
  ): Promise<MenuItem | null> {
    try {
      return await this.service.deleteMenuItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [FavoriteMenuItem], { name: "favoriteMenuItems" })
  @nestAccessControl.UseRoles({
    resource: "FavoriteMenuItem",
    action: "read",
    possession: "any",
  })
  async findFavoriteMenuItems(
    @graphql.Parent() parent: MenuItem,
    @graphql.Args() args: FavoriteMenuItemFindManyArgs
  ): Promise<FavoriteMenuItem[]> {
    const results = await this.service.findFavoriteMenuItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [MenuItemCategory], {
    name: "menuItemCategoriesMenuItemCategoriesMenuItemIdToMenuItems",
  })
  @nestAccessControl.UseRoles({
    resource: "MenuItemCategory",
    action: "read",
    possession: "any",
  })
  async findMenuItemCategoriesMenuItemCategoriesMenuItemIdToMenuItems(
    @graphql.Parent() parent: MenuItem,
    @graphql.Args() args: MenuItemCategoryFindManyArgs
  ): Promise<MenuItemCategory[]> {
    const results =
      await this.service.findMenuItemCategoriesMenuItemCategoriesMenuItemIdToMenuItems(
        parent.id,
        args
      );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [OrderItem], { name: "orderItems" })
  @nestAccessControl.UseRoles({
    resource: "OrderItem",
    action: "read",
    possession: "any",
  })
  async findOrderItems(
    @graphql.Parent() parent: MenuItem,
    @graphql.Args() args: OrderItemFindManyArgs
  ): Promise<OrderItem[]> {
    const results = await this.service.findOrderItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => MenuItemCategory, {
    nullable: true,
    name: "menuItemCategoriesMenuItemsCategoryIdToMenuItemCategories",
  })
  @nestAccessControl.UseRoles({
    resource: "MenuItemCategory",
    action: "read",
    possession: "any",
  })
  async getMenuItemCategoriesMenuItemsCategoryIdToMenuItemCategories(
    @graphql.Parent() parent: MenuItem
  ): Promise<MenuItemCategory | null> {
    const result =
      await this.service.getMenuItemCategoriesMenuItemsCategoryIdToMenuItemCategories(
        parent.id
      );

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Menu, {
    nullable: true,
    name: "menus",
  })
  @nestAccessControl.UseRoles({
    resource: "Menu",
    action: "read",
    possession: "any",
  })
  async getMenus(@graphql.Parent() parent: MenuItem): Promise<Menu | null> {
    const result = await this.service.getMenus(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
