/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TransactionStatusService } from "../transactionStatus.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TransactionStatusCreateInput } from "./TransactionStatusCreateInput";
import { TransactionStatus } from "./TransactionStatus";
import { TransactionStatusFindManyArgs } from "./TransactionStatusFindManyArgs";
import { TransactionStatusWhereUniqueInput } from "./TransactionStatusWhereUniqueInput";
import { TransactionStatusUpdateInput } from "./TransactionStatusUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TransactionStatusControllerBase {
  constructor(
    protected readonly service: TransactionStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TransactionStatus })
  @nestAccessControl.UseRoles({
    resource: "TransactionStatus",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTransactionStatus(
    @common.Body() data: TransactionStatusCreateInput
  ): Promise<TransactionStatus> {
    return await this.service.createTransactionStatus({
      data: {
        ...data,

        transactions: data.transactions
          ? {
              connect: data.transactions,
            }
          : undefined,
      },
      select: {
        id: true,
        status: true,
        statusDate: true,

        transactions: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TransactionStatus] })
  @ApiNestedQuery(TransactionStatusFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TransactionStatus",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async transactionStatuses(
    @common.Req() request: Request
  ): Promise<TransactionStatus[]> {
    const args = plainToClass(TransactionStatusFindManyArgs, request.query);
    return this.service.transactionStatuses({
      ...args,
      select: {
        id: true,
        status: true,
        statusDate: true,

        transactions: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TransactionStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TransactionStatus",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async transactionStatus(
    @common.Param() params: TransactionStatusWhereUniqueInput
  ): Promise<TransactionStatus | null> {
    const result = await this.service.transactionStatus({
      where: params,
      select: {
        id: true,
        status: true,
        statusDate: true,

        transactions: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TransactionStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TransactionStatus",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTransactionStatus(
    @common.Param() params: TransactionStatusWhereUniqueInput,
    @common.Body() data: TransactionStatusUpdateInput
  ): Promise<TransactionStatus | null> {
    try {
      return await this.service.updateTransactionStatus({
        where: params,
        data: {
          ...data,

          transactions: data.transactions
            ? {
                connect: data.transactions,
              }
            : undefined,
        },
        select: {
          id: true,
          status: true,
          statusDate: true,

          transactions: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TransactionStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TransactionStatus",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTransactionStatus(
    @common.Param() params: TransactionStatusWhereUniqueInput
  ): Promise<TransactionStatus | null> {
    try {
      return await this.service.deleteTransactionStatus({
        where: params,
        select: {
          id: true,
          status: true,
          statusDate: true,

          transactions: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
