/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HashtagService } from "../hashtag.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HashtagCreateInput } from "./HashtagCreateInput";
import { Hashtag } from "./Hashtag";
import { HashtagFindManyArgs } from "./HashtagFindManyArgs";
import { HashtagWhereUniqueInput } from "./HashtagWhereUniqueInput";
import { HashtagUpdateInput } from "./HashtagUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HashtagControllerBase {
  constructor(
    protected readonly service: HashtagService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Hashtag })
  @nestAccessControl.UseRoles({
    resource: "Hashtag",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHashtag(
    @common.Body() data: HashtagCreateInput
  ): Promise<Hashtag> {
    return await this.service.createHashtag({
      data: data,
      select: {
        createdAt: true,
        hashText: true,
        id: true,
        tag: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Hashtag] })
  @ApiNestedQuery(HashtagFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Hashtag",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hashtags(@common.Req() request: Request): Promise<Hashtag[]> {
    const args = plainToClass(HashtagFindManyArgs, request.query);
    return this.service.hashtags({
      ...args,
      select: {
        createdAt: true,
        hashText: true,
        id: true,
        tag: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Hashtag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Hashtag",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hashtag(
    @common.Param() params: HashtagWhereUniqueInput
  ): Promise<Hashtag | null> {
    const result = await this.service.hashtag({
      where: params,
      select: {
        createdAt: true,
        hashText: true,
        id: true,
        tag: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Hashtag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Hashtag",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHashtag(
    @common.Param() params: HashtagWhereUniqueInput,
    @common.Body() data: HashtagUpdateInput
  ): Promise<Hashtag | null> {
    try {
      return await this.service.updateHashtag({
        where: params,
        data: data,
        select: {
          createdAt: true,
          hashText: true,
          id: true,
          tag: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Hashtag })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Hashtag",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHashtag(
    @common.Param() params: HashtagWhereUniqueInput
  ): Promise<Hashtag | null> {
    try {
      return await this.service.deleteHashtag({
        where: params,
        select: {
          createdAt: true,
          hashText: true,
          id: true,
          tag: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
