/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PaymentMethodService } from "../paymentMethod.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaymentMethodCreateInput } from "./PaymentMethodCreateInput";
import { PaymentMethod } from "./PaymentMethod";
import { PaymentMethodFindManyArgs } from "./PaymentMethodFindManyArgs";
import { PaymentMethodWhereUniqueInput } from "./PaymentMethodWhereUniqueInput";
import { PaymentMethodUpdateInput } from "./PaymentMethodUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";
import { PaymentFindManyArgs } from "../../payment/base/PaymentFindManyArgs";
import { Payment } from "../../payment/base/Payment";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaymentMethodControllerBase {
  constructor(
    protected readonly service: PaymentMethodService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentMethod })
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPaymentMethod(
    @common.Body() data: PaymentMethodCreateInput
  ): Promise<PaymentMethod> {
    return await this.service.createPaymentMethod({
      data: data,
      select: {
        id: true,
        methodDetails: true,
        methodName: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentMethod] })
  @ApiNestedQuery(PaymentMethodFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentMethods(
    @common.Req() request: Request
  ): Promise<PaymentMethod[]> {
    const args = plainToClass(PaymentMethodFindManyArgs, request.query);
    return this.service.paymentMethods({
      ...args,
      select: {
        id: true,
        methodDetails: true,
        methodName: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentMethod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentMethod(
    @common.Param() params: PaymentMethodWhereUniqueInput
  ): Promise<PaymentMethod | null> {
    const result = await this.service.paymentMethod({
      where: params,
      select: {
        id: true,
        methodDetails: true,
        methodName: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentMethod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePaymentMethod(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() data: PaymentMethodUpdateInput
  ): Promise<PaymentMethod | null> {
    try {
      return await this.service.updatePaymentMethod({
        where: params,
        data: data,
        select: {
          id: true,
          methodDetails: true,
          methodName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentMethod })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePaymentMethod(
    @common.Param() params: PaymentMethodWhereUniqueInput
  ): Promise<PaymentMethod | null> {
    try {
      return await this.service.deletePaymentMethod({
        where: params,
        select: {
          id: true,
          methodDetails: true,
          methodName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "any",
  })
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: PaymentMethodWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        coupons: {
          select: {
            id: true,
          },
        },

        deliveryTime: true,
        discountAmount: true,
        finalAmount: true,
        id: true,
        isDelivered: true,
        isPaid: true,
        orderDate: true,
        orderType: true,

        paymentMethods: {
          select: {
            id: true,
          },
        },

        restaurants: {
          select: {
            id: true,
          },
        },

        scheduledDeliveryTime: true,
        specialInstructions: true,
        status: true,
        totalAmount: true,

        userAddresses: {
          select: {
            id: true,
          },
        },

        userModels: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "update",
    possession: "any",
  })
  async connectOrders(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "update",
    possession: "any",
  })
  async updateOrders(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "update",
    possession: "any",
  })
  async disconnectOrders(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/payments")
  @ApiNestedQuery(PaymentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Payment",
    action: "read",
    possession: "any",
  })
  async findPayments(
    @common.Req() request: Request,
    @common.Param() params: PaymentMethodWhereUniqueInput
  ): Promise<Payment[]> {
    const query = plainToClass(PaymentFindManyArgs, request.query);
    const results = await this.service.findPayments(params.id, {
      ...query,
      select: {
        id: true,

        orders: {
          select: {
            id: true,
          },
        },

        paymentAmount: true,
        paymentDate: true,

        paymentMethods: {
          select: {
            id: true,
          },
        },

        paymentStatus: true,
        transactionId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "update",
    possession: "any",
  })
  async connectPayments(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        connect: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "update",
    possession: "any",
  })
  async updatePayments(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        set: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/payments")
  @nestAccessControl.UseRoles({
    resource: "PaymentMethod",
    action: "update",
    possession: "any",
  })
  async disconnectPayments(
    @common.Param() params: PaymentMethodWhereUniqueInput,
    @common.Body() body: PaymentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      payments: {
        disconnect: body,
      },
    };
    await this.service.updatePaymentMethod({
      where: params,
      data,
      select: { id: true },
    });
  }
}
