/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccessLogListRelationFilter } from "../../accessLog/base/AccessLogListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { CouponRedemptionListRelationFilter } from "../../couponRedemption/base/CouponRedemptionListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { CustomerPreferenceListRelationFilter } from "../../customerPreference/base/CustomerPreferenceListRelationFilter";
import { CustomerSubscriptionListRelationFilter } from "../../customerSubscription/base/CustomerSubscriptionListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { ErrorLogListRelationFilter } from "../../errorLog/base/ErrorLogListRelationFilter";
import { FavoriteListRelationFilter } from "../../favorite/base/FavoriteListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { NotificationListRelationFilter } from "../../notification/base/NotificationListRelationFilter";
import { NotificationSettingListRelationFilter } from "../../notificationSetting/base/NotificationSettingListRelationFilter";
import { OrderListRelationFilter } from "../../order/base/OrderListRelationFilter";
import { ReportListRelationFilter } from "../../report/base/ReportListRelationFilter";
import { ReservationListRelationFilter } from "../../reservation/base/ReservationListRelationFilter";
import { ReviewListRelationFilter } from "../../review/base/ReviewListRelationFilter";
import { RewardListRelationFilter } from "../../reward/base/RewardListRelationFilter";
import { SubscriptionListRelationFilter } from "../../subscription/base/SubscriptionListRelationFilter";
import { TransactionListRelationFilter } from "../../transaction/base/TransactionListRelationFilter";
import { UserAddressListRelationFilter } from "../../userAddress/base/UserAddressListRelationFilter";
import { WishlistListRelationFilter } from "../../wishlist/base/WishlistListRelationFilter";

@InputType()
class UserModelWhereInput {
  @ApiProperty({
    required: false,
    type: () => AccessLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AccessLogListRelationFilter)
  @IsOptional()
  @Field(() => AccessLogListRelationFilter, {
    nullable: true,
  })
  accessLogs?: AccessLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  appleSsoToken?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CouponRedemptionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CouponRedemptionListRelationFilter)
  @IsOptional()
  @Field(() => CouponRedemptionListRelationFilter, {
    nullable: true,
  })
  couponRedemptions?: CouponRedemptionListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  createdAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CustomerPreferenceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CustomerPreferenceListRelationFilter)
  @IsOptional()
  @Field(() => CustomerPreferenceListRelationFilter, {
    nullable: true,
  })
  customerPreferences?: CustomerPreferenceListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CustomerSubscriptionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CustomerSubscriptionListRelationFilter)
  @IsOptional()
  @Field(() => CustomerSubscriptionListRelationFilter, {
    nullable: true,
  })
  customerSubscriptions?: CustomerSubscriptionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  email?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  emailPassword?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ErrorLogListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ErrorLogListRelationFilter)
  @IsOptional()
  @Field(() => ErrorLogListRelationFilter, {
    nullable: true,
  })
  errorLogs?: ErrorLogListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  facebookSsoToken?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FavoriteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FavoriteListRelationFilter)
  @IsOptional()
  @Field(() => FavoriteListRelationFilter, {
    nullable: true,
  })
  favorites?: FavoriteListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  googleSsoToken?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => NotificationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NotificationListRelationFilter)
  @IsOptional()
  @Field(() => NotificationListRelationFilter, {
    nullable: true,
  })
  notifications?: NotificationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => NotificationSettingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NotificationSettingListRelationFilter)
  @IsOptional()
  @Field(() => NotificationSettingListRelationFilter, {
    nullable: true,
  })
  notificationSettings?: NotificationSettingListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => OrderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrderListRelationFilter)
  @IsOptional()
  @Field(() => OrderListRelationFilter, {
    nullable: true,
  })
  orders?: OrderListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  phoneNumber?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReportListRelationFilter)
  @IsOptional()
  @Field(() => ReportListRelationFilter, {
    nullable: true,
  })
  reports?: ReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ReservationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReservationListRelationFilter)
  @IsOptional()
  @Field(() => ReservationListRelationFilter, {
    nullable: true,
  })
  reservations?: ReservationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ReviewListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReviewListRelationFilter)
  @IsOptional()
  @Field(() => ReviewListRelationFilter, {
    nullable: true,
  })
  reviews?: ReviewListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RewardListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RewardListRelationFilter)
  @IsOptional()
  @Field(() => RewardListRelationFilter, {
    nullable: true,
  })
  rewards?: RewardListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SubscriptionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SubscriptionListRelationFilter)
  @IsOptional()
  @Field(() => SubscriptionListRelationFilter, {
    nullable: true,
  })
  subscriptions?: SubscriptionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TransactionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TransactionListRelationFilter)
  @IsOptional()
  @Field(() => TransactionListRelationFilter, {
    nullable: true,
  })
  transactions?: TransactionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  twitterSsoToken?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserAddressListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserAddressListRelationFilter)
  @IsOptional()
  @Field(() => UserAddressListRelationFilter, {
    nullable: true,
  })
  userAddresses?: UserAddressListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WishlistListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WishlistListRelationFilter)
  @IsOptional()
  @Field(() => WishlistListRelationFilter, {
    nullable: true,
  })
  wishlist?: WishlistListRelationFilter;
}

export { UserModelWhereInput as UserModelWhereInput };
