/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Menu, // @ts-ignore
  MenuItem, // @ts-ignore
  Restaurant,
} from "@prisma/client";

export class MenuServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.MenuCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.MenuCountArgs>
  ): Promise<number> {
    return this.prisma.menu.count(args);
  }

  async menus<T extends Prisma.MenuFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MenuFindManyArgs>
  ): Promise<Menu[]> {
    return this.prisma.menu.findMany(args);
  }
  async menu<T extends Prisma.MenuFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MenuFindUniqueArgs>
  ): Promise<Menu | null> {
    return this.prisma.menu.findUnique(args);
  }
  async createMenu<T extends Prisma.MenuCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MenuCreateArgs>
  ): Promise<Menu> {
    return this.prisma.menu.create<T>(args);
  }
  async updateMenu<T extends Prisma.MenuUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MenuUpdateArgs>
  ): Promise<Menu> {
    return this.prisma.menu.update<T>(args);
  }
  async deleteMenu<T extends Prisma.MenuDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.MenuDeleteArgs>
  ): Promise<Menu> {
    return this.prisma.menu.delete(args);
  }

  async findMenuItems(
    parentId: number,
    args: Prisma.MenuItemFindManyArgs
  ): Promise<MenuItem[]> {
    return this.prisma.menu
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .menuItems(args);
  }

  async getRestaurants(parentId: number): Promise<Restaurant | null> {
    return this.prisma.menu
      .findUnique({
        where: { id: parentId },
      })
      .restaurants();
  }
}
