import { AccessLogUpdateManyWithoutUserModelsInput } from "./AccessLogUpdateManyWithoutUserModelsInput";
import { CouponRedemptionUpdateManyWithoutUserModelsInput } from "./CouponRedemptionUpdateManyWithoutUserModelsInput";
import { CustomerPreferenceUpdateManyWithoutUserModelsInput } from "./CustomerPreferenceUpdateManyWithoutUserModelsInput";
import { CustomerSubscriptionUpdateManyWithoutUserModelsInput } from "./CustomerSubscriptionUpdateManyWithoutUserModelsInput";
import { ErrorLogUpdateManyWithoutUserModelsInput } from "./ErrorLogUpdateManyWithoutUserModelsInput";
import { FavoriteUpdateManyWithoutUserModelsInput } from "./FavoriteUpdateManyWithoutUserModelsInput";
import { NotificationUpdateManyWithoutUserModelsInput } from "./NotificationUpdateManyWithoutUserModelsInput";
import { NotificationSettingUpdateManyWithoutUserModelsInput } from "./NotificationSettingUpdateManyWithoutUserModelsInput";
import { OrderUpdateManyWithoutUserModelsInput } from "./OrderUpdateManyWithoutUserModelsInput";
import { ReportUpdateManyWithoutUserModelsInput } from "./ReportUpdateManyWithoutUserModelsInput";
import { ReservationUpdateManyWithoutUserModelsInput } from "./ReservationUpdateManyWithoutUserModelsInput";
import { ReviewUpdateManyWithoutUserModelsInput } from "./ReviewUpdateManyWithoutUserModelsInput";
import { RewardUpdateManyWithoutUserModelsInput } from "./RewardUpdateManyWithoutUserModelsInput";
import { SubscriptionUpdateManyWithoutUserModelsInput } from "./SubscriptionUpdateManyWithoutUserModelsInput";
import { TransactionUpdateManyWithoutUserModelsInput } from "./TransactionUpdateManyWithoutUserModelsInput";
import { UserAddressUpdateManyWithoutUserModelsInput } from "./UserAddressUpdateManyWithoutUserModelsInput";
import { WishlistUpdateManyWithoutUserModelsInput } from "./WishlistUpdateManyWithoutUserModelsInput";

export type UserModelUpdateInput = {
  accessLogs?: AccessLogUpdateManyWithoutUserModelsInput;
  appleSsoToken?: string | null;
  couponRedemptions?: CouponRedemptionUpdateManyWithoutUserModelsInput;
  customerPreferences?: CustomerPreferenceUpdateManyWithoutUserModelsInput;
  customerSubscriptions?: CustomerSubscriptionUpdateManyWithoutUserModelsInput;
  email?: string;
  emailPassword?: string;
  errorLogs?: ErrorLogUpdateManyWithoutUserModelsInput;
  facebookSsoToken?: string | null;
  favorites?: FavoriteUpdateManyWithoutUserModelsInput;
  googleSsoToken?: string | null;
  name?: string | null;
  notifications?: NotificationUpdateManyWithoutUserModelsInput;
  notificationSettings?: NotificationSettingUpdateManyWithoutUserModelsInput;
  orders?: OrderUpdateManyWithoutUserModelsInput;
  phoneNumber?: string;
  reports?: ReportUpdateManyWithoutUserModelsInput;
  reservations?: ReservationUpdateManyWithoutUserModelsInput;
  reviews?: ReviewUpdateManyWithoutUserModelsInput;
  rewards?: RewardUpdateManyWithoutUserModelsInput;
  subscriptions?: SubscriptionUpdateManyWithoutUserModelsInput;
  transactions?: TransactionUpdateManyWithoutUserModelsInput;
  twitterSsoToken?: string | null;
  updatedAt?: Date | null;
  userAddresses?: UserAddressUpdateManyWithoutUserModelsInput;
  wishlist?: WishlistUpdateManyWithoutUserModelsInput;
};
