import { AccessLogListRelationFilter } from "../accessLog/AccessLogListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { CouponRedemptionListRelationFilter } from "../couponRedemption/CouponRedemptionListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { CustomerPreferenceListRelationFilter } from "../customerPreference/CustomerPreferenceListRelationFilter";
import { CustomerSubscriptionListRelationFilter } from "../customerSubscription/CustomerSubscriptionListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { ErrorLogListRelationFilter } from "../errorLog/ErrorLogListRelationFilter";
import { FavoriteListRelationFilter } from "../favorite/FavoriteListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { NotificationListRelationFilter } from "../notification/NotificationListRelationFilter";
import { NotificationSettingListRelationFilter } from "../notificationSetting/NotificationSettingListRelationFilter";
import { OrderListRelationFilter } from "../order/OrderListRelationFilter";
import { ReportListRelationFilter } from "../report/ReportListRelationFilter";
import { ReservationListRelationFilter } from "../reservation/ReservationListRelationFilter";
import { ReviewListRelationFilter } from "../review/ReviewListRelationFilter";
import { RewardListRelationFilter } from "../reward/RewardListRelationFilter";
import { SubscriptionListRelationFilter } from "../subscription/SubscriptionListRelationFilter";
import { TransactionListRelationFilter } from "../transaction/TransactionListRelationFilter";
import { UserAddressListRelationFilter } from "../userAddress/UserAddressListRelationFilter";
import { WishlistListRelationFilter } from "../wishlist/WishlistListRelationFilter";

export type UserModelWhereInput = {
  accessLogs?: AccessLogListRelationFilter;
  appleSsoToken?: StringNullableFilter;
  couponRedemptions?: CouponRedemptionListRelationFilter;
  createdAt?: DateTimeNullableFilter;
  customerPreferences?: CustomerPreferenceListRelationFilter;
  customerSubscriptions?: CustomerSubscriptionListRelationFilter;
  email?: StringFilter;
  emailPassword?: StringFilter;
  errorLogs?: ErrorLogListRelationFilter;
  facebookSsoToken?: StringNullableFilter;
  favorites?: FavoriteListRelationFilter;
  googleSsoToken?: StringNullableFilter;
  id?: IntFilter;
  name?: StringNullableFilter;
  notifications?: NotificationListRelationFilter;
  notificationSettings?: NotificationSettingListRelationFilter;
  orders?: OrderListRelationFilter;
  phoneNumber?: StringFilter;
  reports?: ReportListRelationFilter;
  reservations?: ReservationListRelationFilter;
  reviews?: ReviewListRelationFilter;
  rewards?: RewardListRelationFilter;
  subscriptions?: SubscriptionListRelationFilter;
  transactions?: TransactionListRelationFilter;
  twitterSsoToken?: StringNullableFilter;
  updatedAt?: DateTimeNullableFilter;
  userAddresses?: UserAddressListRelationFilter;
  wishlist?: WishlistListRelationFilter;
};
