import { AccessLog } from "../accessLog/AccessLog";
import { CouponRedemption } from "../couponRedemption/CouponRedemption";
import { CustomerPreference } from "../customerPreference/CustomerPreference";
import { CustomerSubscription } from "../customerSubscription/CustomerSubscription";
import { ErrorLog } from "../errorLog/ErrorLog";
import { Favorite } from "../favorite/Favorite";
import { Notification } from "../notification/Notification";
import { NotificationSetting } from "../notificationSetting/NotificationSetting";
import { Order } from "../order/Order";
import { Report } from "../report/Report";
import { Reservation } from "../reservation/Reservation";
import { Review } from "../review/Review";
import { Reward } from "../reward/Reward";
import { Subscription } from "../subscription/Subscription";
import { Transaction } from "../transaction/Transaction";
import { UserAddress } from "../userAddress/UserAddress";
import { Wishlist } from "../wishlist/Wishlist";

export type UserModel = {
  accessLogs?: Array<AccessLog>;
  appleSsoToken: string | null;
  couponRedemptions?: Array<CouponRedemption>;
  createdAt: Date | null;
  customerPreferences?: Array<CustomerPreference>;
  customerSubscriptions?: Array<CustomerSubscription>;
  email: string;
  emailPassword: string;
  errorLogs?: Array<ErrorLog>;
  facebookSsoToken: string | null;
  favorites?: Array<Favorite>;
  googleSsoToken: string | null;
  id: number;
  name: string | null;
  notifications?: Array<Notification>;
  notificationSettings?: Array<NotificationSetting>;
  orders?: Array<Order>;
  phoneNumber: string;
  reports?: Array<Report>;
  reservations?: Array<Reservation>;
  reviews?: Array<Review>;
  rewards?: Array<Reward>;
  subscriptions?: Array<Subscription>;
  transactions?: Array<Transaction>;
  twitterSsoToken: string | null;
  updatedAt: Date | null;
  userAddresses?: Array<UserAddress>;
  wishlist?: Array<Wishlist>;
};
