/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CustomerPreference, // @ts-ignore
  UserModel,
} from "@prisma/client";

export class CustomerPreferenceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CustomerPreferenceCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CustomerPreferenceCountArgs>
  ): Promise<number> {
    return this.prisma.customerPreference.count(args);
  }

  async customerPreferences<T extends Prisma.CustomerPreferenceFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CustomerPreferenceFindManyArgs>
  ): Promise<CustomerPreference[]> {
    return this.prisma.customerPreference.findMany(args);
  }
  async customerPreference<T extends Prisma.CustomerPreferenceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CustomerPreferenceFindUniqueArgs>
  ): Promise<CustomerPreference | null> {
    return this.prisma.customerPreference.findUnique(args);
  }
  async createCustomerPreference<T extends Prisma.CustomerPreferenceCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CustomerPreferenceCreateArgs>
  ): Promise<CustomerPreference> {
    return this.prisma.customerPreference.create<T>(args);
  }
  async updateCustomerPreference<T extends Prisma.CustomerPreferenceUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CustomerPreferenceUpdateArgs>
  ): Promise<CustomerPreference> {
    return this.prisma.customerPreference.update<T>(args);
  }
  async deleteCustomerPreference<T extends Prisma.CustomerPreferenceDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CustomerPreferenceDeleteArgs>
  ): Promise<CustomerPreference> {
    return this.prisma.customerPreference.delete(args);
  }

  async getUserModels(parentId: number): Promise<UserModel | null> {
    return this.prisma.customerPreference
      .findUnique({
        where: { id: parentId },
      })
      .userModels();
  }
}
