/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FavoriteMenuItemService } from "../favoriteMenuItem.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FavoriteMenuItemCreateInput } from "./FavoriteMenuItemCreateInput";
import { FavoriteMenuItem } from "./FavoriteMenuItem";
import { FavoriteMenuItemFindManyArgs } from "./FavoriteMenuItemFindManyArgs";
import { FavoriteMenuItemWhereUniqueInput } from "./FavoriteMenuItemWhereUniqueInput";
import { FavoriteMenuItemUpdateInput } from "./FavoriteMenuItemUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FavoriteMenuItemControllerBase {
  constructor(
    protected readonly service: FavoriteMenuItemService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FavoriteMenuItem })
  @nestAccessControl.UseRoles({
    resource: "FavoriteMenuItem",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFavoriteMenuItem(
    @common.Body() data: FavoriteMenuItemCreateInput
  ): Promise<FavoriteMenuItem> {
    return await this.service.createFavoriteMenuItem({
      data: {
        ...data,

        favorites: data.favorites
          ? {
              connect: data.favorites,
            }
          : undefined,

        menuItems: data.menuItems
          ? {
              connect: data.menuItems,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        favorites: {
          select: {
            id: true,
          },
        },

        id: true,

        menuItems: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FavoriteMenuItem] })
  @ApiNestedQuery(FavoriteMenuItemFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FavoriteMenuItem",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async favoriteMenuItems(
    @common.Req() request: Request
  ): Promise<FavoriteMenuItem[]> {
    const args = plainToClass(FavoriteMenuItemFindManyArgs, request.query);
    return this.service.favoriteMenuItems({
      ...args,
      select: {
        createdAt: true,

        favorites: {
          select: {
            id: true,
          },
        },

        id: true,

        menuItems: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FavoriteMenuItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FavoriteMenuItem",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async favoriteMenuItem(
    @common.Param() params: FavoriteMenuItemWhereUniqueInput
  ): Promise<FavoriteMenuItem | null> {
    const result = await this.service.favoriteMenuItem({
      where: params,
      select: {
        createdAt: true,

        favorites: {
          select: {
            id: true,
          },
        },

        id: true,

        menuItems: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FavoriteMenuItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FavoriteMenuItem",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFavoriteMenuItem(
    @common.Param() params: FavoriteMenuItemWhereUniqueInput,
    @common.Body() data: FavoriteMenuItemUpdateInput
  ): Promise<FavoriteMenuItem | null> {
    try {
      return await this.service.updateFavoriteMenuItem({
        where: params,
        data: {
          ...data,

          favorites: data.favorites
            ? {
                connect: data.favorites,
              }
            : undefined,

          menuItems: data.menuItems
            ? {
                connect: data.menuItems,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          favorites: {
            select: {
              id: true,
            },
          },

          id: true,

          menuItems: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FavoriteMenuItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FavoriteMenuItem",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFavoriteMenuItem(
    @common.Param() params: FavoriteMenuItemWhereUniqueInput
  ): Promise<FavoriteMenuItem | null> {
    try {
      return await this.service.deleteFavoriteMenuItem({
        where: params,
        select: {
          createdAt: true,

          favorites: {
            select: {
              id: true,
            },
          },

          id: true,

          menuItems: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
