/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReviewRatingService } from "../reviewRating.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReviewRatingCreateInput } from "./ReviewRatingCreateInput";
import { ReviewRating } from "./ReviewRating";
import { ReviewRatingFindManyArgs } from "./ReviewRatingFindManyArgs";
import { ReviewRatingWhereUniqueInput } from "./ReviewRatingWhereUniqueInput";
import { ReviewRatingUpdateInput } from "./ReviewRatingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReviewRatingControllerBase {
  constructor(
    protected readonly service: ReviewRatingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReviewRating })
  @nestAccessControl.UseRoles({
    resource: "ReviewRating",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReviewRating(
    @common.Body() data: ReviewRatingCreateInput
  ): Promise<ReviewRating> {
    return await this.service.createReviewRating({
      data: {
        ...data,

        reviews: data.reviews
          ? {
              connect: data.reviews,
            }
          : undefined,
      },
      select: {
        cleanliness: true,
        foodQuality: true,
        id: true,

        reviews: {
          select: {
            id: true,
          },
        },

        service: true,
        valueForMoney: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReviewRating] })
  @ApiNestedQuery(ReviewRatingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ReviewRating",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewRatings(@common.Req() request: Request): Promise<ReviewRating[]> {
    const args = plainToClass(ReviewRatingFindManyArgs, request.query);
    return this.service.reviewRatings({
      ...args,
      select: {
        cleanliness: true,
        foodQuality: true,
        id: true,

        reviews: {
          select: {
            id: true,
          },
        },

        service: true,
        valueForMoney: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReviewRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewRating",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reviewRating(
    @common.Param() params: ReviewRatingWhereUniqueInput
  ): Promise<ReviewRating | null> {
    const result = await this.service.reviewRating({
      where: params,
      select: {
        cleanliness: true,
        foodQuality: true,
        id: true,

        reviews: {
          select: {
            id: true,
          },
        },

        service: true,
        valueForMoney: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReviewRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewRating",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReviewRating(
    @common.Param() params: ReviewRatingWhereUniqueInput,
    @common.Body() data: ReviewRatingUpdateInput
  ): Promise<ReviewRating | null> {
    try {
      return await this.service.updateReviewRating({
        where: params,
        data: {
          ...data,

          reviews: data.reviews
            ? {
                connect: data.reviews,
              }
            : undefined,
        },
        select: {
          cleanliness: true,
          foodQuality: true,
          id: true,

          reviews: {
            select: {
              id: true,
            },
          },

          service: true,
          valueForMoney: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReviewRating })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReviewRating",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReviewRating(
    @common.Param() params: ReviewRatingWhereUniqueInput
  ): Promise<ReviewRating | null> {
    try {
      return await this.service.deleteReviewRating({
        where: params,
        select: {
          cleanliness: true,
          foodQuality: true,
          id: true,

          reviews: {
            select: {
              id: true,
            },
          },

          service: true,
          valueForMoney: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
