/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SystemSettingService } from "../systemSetting.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SystemSettingCreateInput } from "./SystemSettingCreateInput";
import { SystemSetting } from "./SystemSetting";
import { SystemSettingFindManyArgs } from "./SystemSettingFindManyArgs";
import { SystemSettingWhereUniqueInput } from "./SystemSettingWhereUniqueInput";
import { SystemSettingUpdateInput } from "./SystemSettingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SystemSettingControllerBase {
  constructor(
    protected readonly service: SystemSettingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SystemSetting })
  @nestAccessControl.UseRoles({
    resource: "SystemSetting",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSystemSetting(
    @common.Body() data: SystemSettingCreateInput
  ): Promise<SystemSetting> {
    return await this.service.createSystemSetting({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        settingKey: true,
        settingValue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SystemSetting] })
  @ApiNestedQuery(SystemSettingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SystemSetting",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async systemSettings(
    @common.Req() request: Request
  ): Promise<SystemSetting[]> {
    const args = plainToClass(SystemSettingFindManyArgs, request.query);
    return this.service.systemSettings({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        settingKey: true,
        settingValue: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SystemSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SystemSetting",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async systemSetting(
    @common.Param() params: SystemSettingWhereUniqueInput
  ): Promise<SystemSetting | null> {
    const result = await this.service.systemSetting({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        settingKey: true,
        settingValue: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SystemSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SystemSetting",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSystemSetting(
    @common.Param() params: SystemSettingWhereUniqueInput,
    @common.Body() data: SystemSettingUpdateInput
  ): Promise<SystemSetting | null> {
    try {
      return await this.service.updateSystemSetting({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          settingKey: true,
          settingValue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SystemSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SystemSetting",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSystemSetting(
    @common.Param() params: SystemSettingWhereUniqueInput
  ): Promise<SystemSetting | null> {
    try {
      return await this.service.deleteSystemSetting({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          settingKey: true,
          settingValue: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
